### ISSUE TITLE
Visual Studio attempts to build with 'all' target instead of 'ALL_BUILD'

### ISSUE THREAD

**Issue by harrishancock** [vector-of-bool/vscode-cmake-tools#102] opened 2017-01-15 02:25 UTC
When attempting to build a project with the Visual Studio 14 2015 CMake generator, I get the following error message:

```
[vscode] Executing command: cmake --build c:/Users/vortr/git/vor/build --target all --config Release -- /m /property:GenerateFullPaths=true
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: all.vcxproj
[vscode] cmake exited with return code 1
```

This seems to be the troublesome line:
https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/common.ts#L682

`this.allTargetName` correctly evaluates to `ALL_BUILD`, but `this.defaultBuildTarget` evaluates to `all`, which overrides it (I guess -- I don't know much TypeScript).

I reproduced this problem on both 0.8.7 and the current develop branch.

**Comment by vector-of-bool** [comment] 2017-01-15 23:13
Looks like a recent refactor broke this behavior for a few contexts. I'll see about fixing it.

**Comment by vector-of-bool** [comment] 2017-01-16 17:27
Should be fixed now

**Closed by vector-of-bool** 2017-01-16 17:27 UTC
Labels: bug

**Comment by harrishancock** [comment] 2017-01-16 17:42
Awesome, thank you!

**Comment by alex94puchades** [comment] 2018-05-20 23:32
I have this very same issue with version 0.11.1

**Comment by vector-of-bool** [comment] 2018-05-20 23:42
Possible regression. You shouldn't need to work around this, but does it continue to use `all` after you reload the window?

**Comment by alex94puchades** [comment] 2018-05-20 23:53
Oops I just tried manually selecting the "ALL_BUILD" target in the status bar and now the "all" target is gone, F7 builds the ALL_BUILD target and everything works. I made sure by cleaning and rebuilding again, so I can confirm 0.11.1 is fine, sorry 😅 (btw thanks a lot for this package)
