### ISSUE TITLE
Build env detect fails to find VS 14

### ISSUE THREAD

**Issue by MathiasMagnus** [vector-of-bool/vscode-cmake-tools#83] opened 2016-11-18 14:04 UTC
Hi!

This build env detect is awesome, but not really working just yet. I opened up Code plain (no dev cmd prompt) and went ahead with the button in the bottom right. It showed me VS 12 (most likely because old WP 8.1 SDK is installed in VS14 and that brings the old toolset), but VS14 is not detected. VS14 is not installed in a default place, but the vcvarsXXX.bat files nonetheless could be found relative to the VS140COMNTOOLS environmental variable which was set by the installer (and points to the non-default install path).

VS15 support would be awesome too. The build tools layout changed slightly, but at least it's documented [here](https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/).

Keep up the awesome work. I already started moving from Big Brother VS to VS Code thanks to your extension. If development continues at this pace, I'll never look back. ;)

**Comment by MathiasMagnus** [comment] 2016-11-18 14:06
Did anyone try with the Standalone Build Tools? I got VS14 installed and will have to keep it that way for the time being, so I cannot test it.

**Comment by vector-of-bool** [comment] 2016-11-18 17:06
I've been using it with the standalone build tools at home without trouble, and that may be the only case that is working in full. My other box with VS 2013 is not working. This feature definitely needs some polish.

I'd greatly appreciate testing, help, and feedback: I have a limited environment, time, and manpower (just me). There are lots of variations in the ways VS can be installed, and I can't explore them all myself.

PRs and error messages are welcome.

**Comment by vector-of-bool** [comment] 2016-11-20 05:59
Latest `0.8.2` release should be a bit more reliable. Still doesn't support VS 2017 though. That may take a bit more work. I'll leave this open for a while in case anyone else is still having trouble.

**Comment by MathiasMagnus** [comment] 2016-11-20 13:30
I deleted a cmaketools.json file and the build dir while a workspace was opened, and after I selected VS14. Now I cannot Configure, because it says "Cannot read 'entries' from undefined. The new cmaketools.json looks like this.

```
{
  "variant": null
}
```

How can I solve this?

**Comment by vector-of-bool** [comment] 2016-11-20 15:40
Does it still do this after restarting vscode? I may have to do another patch release today if this isn't easily fixed...

**Comment by MathiasMagnus** [comment] 2016-11-20 17:11
Yes, cleaned out the folder, no .vscode folder, just CMakeLists.txt, close Code and back, no dev env button, neither can it configure.

**Comment by vector-of-bool** [comment] 2016-11-20 20:04
Try again with `0.8.3`. I tweaked some environment loading code but wasn't able to reproduce the issue completely.

**Comment by MathiasMagnus** [comment] 2016-11-21 10:32
The issue remains, even though I uninstalled Code, deleted all temporary files I found under my users Home. I was surprised thought that when I reinstalled Code, the extensions remained installed. Where do the extensions install? I want to start COMPLETELY afresh.

**Comment by vector-of-bool** [comment] 2016-11-21 16:09
I'm not entirely sure where extensions go on Windows.

Could you open the devtools inside of code and paste here the traceback for the error that you are seeing?

**Comment by vector-of-bool** [comment] 2016-11-21 16:11
Looks like you aren't the only one: Let's move to #85

**Comment by vector-of-bool** [comment] 2016-11-22 04:57
I'll close this issue and defer to #85, which should also be fixed.

**Closed by vector-of-bool** 2016-11-22 04:57 UTC
Labels: bug, feedback wanted!, help wanted
