### ISSUE TITLE
CMake extension icon disappears for 1.1.3

### ISSUE THREAD

**Issue by j-m** [vector-of-bool/vscode-cmake-tools#663] opened 2019-03-26 00:36 UTC
### Brief Issue Summary

All CMake commands (quickStart, configure, etc) become unrecognised and the extension icon disappears when upgrading to 1.1.3.

### Expected:

1. Install 1.1.2 of CMake Tools
2. See CMake Tools extension icon
3. Be able to run CMake commands with F1 like `CMake: quick start`

1. Upgrade to 1.1.3 CMake Tools
2. See CMake Tools extension icon
3. Be able to run CMake commands with F1 like `CMake: quick start`

### Apparent Behavior:

1. Install 1.1.2 of CMake Tools
2. See CMake Tools extension icon
3. Be able to run CMake commands with F1 like `CMake: quick start`

1. Upgrade to 1.1.3 CMake Tools
2. No CMake Tools extension icon visible
3.  F1 `CMake: quick start` and a popup shows "command 'cmake.configure' not found"

### CMake Tools Log

No useful logs

### Developer Tools Log

No useful logs

### Platform and Versions

- **Operating System**: Windows 
- **CMake Version**: cmake-3.14.0-win64-x64
- **VSCode Version**: 1.32.3
- **CMake Tools Extension Version**: 1.1.2 -> 1.1.3
- **Compiler/Toolchain**: N/A

### Other Notes/Information

1.1.3 has previously worked for me.
This week I had to reinstall Windows and lost all of my programs, so it's likely that I have misconfigured something; although it's odd that the extension partially works in 1.1.2 but not 1.1.3.
I have not installed ANY compilers yet but I would have expected the extension to at least somewhat work without one. Or does something in the 1.1.2 -> 1.1.3 update warrant this?

**Comment by dcourtois** [comment] 2019-04-05 09:40
Hi,
I can't say exactly what's happening to you, but one thing's for certain: the CMake commands should work, no matter what compiler you have installed (or have not) So if quick start pops up telling that a cmake command isn't found, it's not related to that.
My guess is that there was some configuration issue unrelated to CMake Tools: I'm on Windows too and updated from 1.1.2 to 1.1.3 when the 1.1.3 was released, and it worked fine.
Also installing the 1.1.3 on a fresh VSCode install works fine.
Is the CMake Tools addon still not working on your setup, or did you manage to make it work ? If the later, you probably can close the issue: even if it's a problem with the addon, since it's impossible to reproduce, it's almost impossible to fix :/

**Comment by j-m** [comment] 2019-04-05 17:05
I have just tried 1.1.3 again and it all works fine.
It's probably best for this to be closed because, as you said, it's probably unlikely to occur to anyone else.
A few things to note: 
- I now have MinGW, Ninja, and Visual Studio compilers installed
- I have since deleted the CMake build folder and rebuilt it from fresh
- I had used multiple versions of CMake (not at the same time)

**Comment by Randshot** [comment] 2019-04-05 19:16
OK, I will close this for now. Btw, you can also close issues you opened.

**Closed by Randshot** 2019-04-05 19:16 UTC
Labels: need info

**Comment by j-m** [comment] 2019-04-05 22:05
I have downgraded to 1.1.2 again.
The extension icon and commands work as normal but I get build errors such as: 
"Cannot open include file: 'string': No such file or directory"
"Cannot open include file: 'map': No such file or directory"
I thought it might be to do with my CMakeLists.txt but it seems odd that there are no issues in 1.1.2 but there are in 1.1.3

**Comment by j-m** [comment] 2019-04-05 23:26
Ignore that. Seems my c_cpp_properties.json became corrupt and for whatever reason, odd that 1.1.2 still worked - must've been a cache as I didn't rebuild.
